# Generated by Django 2.1 on 2020-04-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_songsim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='歌曲名字'),
        ),
    ]
