# Generated by Django 2.1 on 2020-04-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_sing_id',
            field=models.CharField(blank=True, max_length=500, verbose_name='歌手ID'),
        ),
    ]
