# Generated by Django 2.1 on 2020-04-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userplaylistrec_usersingrec_usersongrec_useruserrec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_sign',
            field=models.TextField(blank=True, max_length=10000, verbose_name='用户签名'),
        ),
    ]
