# Generated by Django 2.1 on 2020-04-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_password',
            # field=models.CharField(default='DUTyIirqMmyFfzuOLS1xBJ8Hib/Sb0UywQYP8/DKJKyVu4bzC7MbAtxUyXCPBbX0gzGgbute0PnWkq9cvJS9KzYRyAz67U4DcbLFRjTtzukpYMWrCi+CWTUzzoUbQXgg1TeV2lHbfX/QobJ+ZzegPHkX/3QIWOUUA9QegmYmHW721It/oq986J0e6ybqt2ZymEyY/DN0pb5f6V4CrR51n0mpVx0ye0tTtQ8ksrwP4UjS9LlOQLFThtxDRoxwu2pXox6zFwZwT8wf+N0t7bPPACf9n7WZQXBxPW6uU9uvcP/HSA8e1YUCVpk6XuPUJE4hNHPBihpeCrsaHN6Euoa1uw==', max_length=20, verbose_name='用户密码'),
            field=models.CharField(
                default='',
                max_length=20, verbose_name='用户密码'),
        ),
    ]
