# Generated by Django 2.1 on 2020-04-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_default_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_phone',
            field=models.CharField(max_length=64, verbose_name='用户手机'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_password',
            field=models.CharField(max_length=3000, verbose_name='用户密码'),
        ),
    ]
